name: Tests

on:
  push:
    branches: [ main, 11.x, 10.x, 9.x ]
  pull_request:
    branches: [ main, 11.x, 10.x, 9.x ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # This matrix will be filtered by branch requirements in the steps
          - php: 8.0
          - php: 8.1
          - php: 8.2
          - php: 8.3

    name: PHP ${{ matrix.php }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Check PHP version compatibility with branch
      id: php-check
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        echo "Branch: $BRANCH_NAME"
        echo "PHP: ${{ matrix.php }}"
        
        # Define PHP requirements for each branch
        case "$BRANCH_NAME" in
          "main")
            # Laravel 12.x requires PHP 8.2+
            if [[ "${{ matrix.php }}" < "8.2" ]]; then
              echo "skip=true" >> $GITHUB_OUTPUT
              echo "Skipping PHP ${{ matrix.php }} for Laravel 12.x (main branch)"
            else
              echo "skip=false" >> $GITHUB_OUTPUT
            fi
            ;;
          "11.x")
            # Laravel 11.x requires PHP 8.2+
            if [[ "${{ matrix.php }}" < "8.2" ]]; then
              echo "skip=true" >> $GITHUB_OUTPUT
              echo "Skipping PHP ${{ matrix.php }} for Laravel 11.x"
            else
              echo "skip=false" >> $GITHUB_OUTPUT
            fi
            ;;
          "10.x")
            # Laravel 10.x requires PHP 8.1+
            if [[ "${{ matrix.php }}" < "8.1" ]]; then
              echo "skip=true" >> $GITHUB_OUTPUT
              echo "Skipping PHP ${{ matrix.php }} for Laravel 10.x"
            else
              echo "skip=false" >> $GITHUB_OUTPUT
            fi
            ;;
          "9.x")
            # Laravel 9.x requires PHP 8.0+
            echo "skip=false" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Unknown branch: $BRANCH_NAME"
            ;;
        esac

    - name: Setup PHP
      if: steps.php-check.outputs.skip == 'false'
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: none

    - name: Setup problem matchers
      if: steps.php-check.outputs.skip == 'false'
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install dependencies
      if: steps.php-check.outputs.skip == 'false'
      run: composer update --prefer-dist --no-interaction

    - name: Dump autoloader
      if: steps.php-check.outputs.skip == 'false'
      run: composer dump-autoload

    - name: List Installed Dependencies
      if: steps.php-check.outputs.skip == 'false'
      run: composer show -D

    - name: Execute tests
      if: steps.php-check.outputs.skip == 'false'
      run: vendor/bin/phpunit

  coverage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: xdebug

    - name: Install dependencies
      run: |
        composer require "laravel/framework:12.*" "orchestra/testbench:10.*" "phpunit/phpunit:^11.5" --no-interaction --no-update
        composer update --prefer-dist --no-interaction

    - name: Dump autoloader
      run: composer dump-autoload

    - name: Execute tests with coverage
      run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.clover
        flags: unittests
        name: codecov-umbrella