name: Tests

on:
  push:
    branches: [ main, 11.x, 10.x, 9.x ]
  pull_request:
    branches: [ main, 11.x, 10.x, 9.x ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          # Laravel 12.x (main branch)
          - laravel: 12.*
            php: 8.2
            testbench: 10.*
            phpunit: ^11.5
            branch: main
          - laravel: 12.*
            php: 8.3
            testbench: 10.*
            phpunit: ^11.5
            branch: main
          - laravel: 12.*
            php: 8.3
            testbench: 10.*
            phpunit: ^12.0
            branch: main
            
          # Laravel 11.x
          - laravel: 11.*
            php: 8.2
            testbench: 9.*
            phpunit: ^10.5
            branch: 11.x
          - laravel: 11.*
            php: 8.3
            testbench: 9.*
            phpunit: ^10.5
            branch: 11.x
          - laravel: 11.*
            php: 8.3
            testbench: 9.*
            phpunit: ^11.3
            branch: 11.x
            
          # Laravel 10.x
          - laravel: 10.*
            php: 8.1
            testbench: 8.*
            phpunit: ^9.6
            branch: 10.x
          - laravel: 10.*
            php: 8.2
            testbench: 8.*
            phpunit: ^9.6
            branch: 10.x
          - laravel: 10.*
            php: 8.3
            testbench: 8.*
            phpunit: ^10.1
            branch: 10.x
            
          # Laravel 9.x
          - laravel: 9.*
            php: 8.0
            testbench: 7.*
            phpunit: ^9.6
            branch: 9.x
          - laravel: 9.*
            php: 8.1
            testbench: 7.*
            phpunit: ^9.6
            branch: 9.x
          - laravel: 9.*
            php: 8.2
            testbench: 7.*
            phpunit: ^10.1
            branch: 9.x

    name: Laravel ${{ matrix.laravel }} - PHP ${{ matrix.php }} - PHPUnit ${{ matrix.phpunit }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: none

    - name: Setup problem matchers
      run: |
        echo "::add-matcher::${{ runner.tool_cache }}/php.json"
        echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

    - name: Install dependencies
      run: |
        composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "phpunit/phpunit:${{ matrix.phpunit }}" --no-interaction --no-update
        composer update --prefer-dist --no-interaction

    - name: List Installed Dependencies
      run: composer show -D

    - name: Execute tests
      run: vendor/bin/phpunit --verbose

  coverage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: xdebug

    - name: Install dependencies
      run: |
        composer require "laravel/framework:12.*" "orchestra/testbench:10.*" "phpunit/phpunit:^11.5" --no-interaction --no-update
        composer update --prefer-dist --no-interaction

    - name: Execute tests with coverage
      run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.clover
        flags: unittests
        name: codecov-umbrella